'use client';


import { Building2, MapPin, Phone, Mail, Hash } from 'lucide-react';
import { cn } from '@/utils';
import type { StoreWizardData } from './wizard.types';
import type { BusinessType } from '@/shared/types/store';

interface Props {
    data: StoreWizardData;
    errors: Record<string, string>;
    update: (field: keyof StoreWizardData, value: any) => void;
    isEdit: boolean;
}

const I = 'w-full px-4 py-3.5 bg-slate-50 border-2 border-slate-100 rounded-xl text-sm font-bold text-slate-900 focus:bg-white focus:border-slate-900 outline-none transition-all';
const L = 'text-[10px] font-black text-slate-600 uppercase tracking-widest flex items-center gap-1';
const S = cn(I, 'appearance-none');


const PROVINCES = ['Ontario','British Columbia','Quebec','Alberta','Manitoba','Saskatchewan','Nova Scotia','New Brunswick','Newfoundland','Prince Edward Island'];
const TIMEZONES = ['America/Toronto','America/Chicago','America/Denver','America/Los_Angeles','America/Halifax','America/Vancouver','America/Winnipeg','America/Edmonton','America/St_Johns'];

const BIZ_TYPES: { value: BusinessType; label: string; desc: string }[] = [
    { value: 'single_store', label: 'Single Store', desc: 'One location business' },
    { value: 'franchise', label: 'Franchise', desc: 'Franchise-operated location' },
    { value: 'corporate', label: 'Corporate', desc: 'Company-owned location' },
    { value: 'ghost_kitchen', label: 'Ghost Kitchen', desc: 'Delivery-only kitchen' },
];

export function WizardStepBasicInfo({ data, errors, update, isEdit }: Props) {
    return (
        <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
            {/* Business Type */}
            <section>
                <h4 className="text-[11px] font-black text-slate-600 uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
                    <span className="w-1 h-4 rounded-full bg-slate-900" /> Business Type
                </h4>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {BIZ_TYPES.map(bt => (
                        <button key={bt.value} type="button" onClick={() => update('businessType', bt.value)}
                            className={cn(
                                'p-4 rounded-2xl border-2 text-left transition-all',
                                data.businessType === bt.value
                                    ? 'bg-slate-900 border-slate-900 text-white scale-[1.02] shadow-lg'
                                    : 'bg-white border-slate-100 text-slate-600 hover:border-slate-300'
                            )}>
                            <span className="text-xs font-black block">{bt.label}</span>
                            <span className={cn('text-[10px] font-medium', data.businessType === bt.value ? 'text-slate-300' : 'text-slate-500')}>{bt.desc}</span>
                        </button>
                    ))}
                </div>
            </section>

            {/* Identity */}
            <section>
                <h4 className="text-[11px] font-black text-slate-600 uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
                    <span className="w-1 h-4 rounded-full bg-emerald-500" />
                    <Building2 size={13} /> Store Identity
                </h4>
                <div className="space-y-1.5">
                    <label className={L}>Store Name <span className="text-rose-500">*</span></label>
                    <input value={data.name} onChange={e => update('name', e.target.value)} placeholder="Downtown Toronto"
                        className={cn(I, errors.name && 'border-rose-300 focus:border-rose-500')} />
                    {errors.name && <p className="text-[10px] text-rose-500 font-bold">{errors.name}</p>}
                    <p className="text-[9px] text-slate-400 font-medium">Store code & URL will be auto-generated by the system</p>
                </div>
            </section>

            {/* Address */}
            <section>
                <h4 className="text-[11px] font-black text-slate-600 uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
                    <span className="w-1 h-4 rounded-full bg-blue-500" />
                    <MapPin size={13} /> Address
                </h4>
                <div className="space-y-4">
                    <div className="space-y-1.5">
                        <label className={L}>Street Address</label>
                        <input value={data.address} onChange={e => update('address', e.target.value)} placeholder="123 Main St" className={I} />
                    </div>
                    <div className="grid grid-cols-3 gap-4">
                        <div className="space-y-1.5">
                            <label className={L}>City <span className="text-rose-500">*</span></label>
                            <input value={data.city} onChange={e => update('city', e.target.value)}
                                className={cn(I, errors.city && 'border-rose-300')} />
                            {errors.city && <p className="text-[10px] text-rose-500 font-bold">{errors.city}</p>}
                        </div>
                        <div className="space-y-1.5">
                            <label className={L}>Province</label>
                            <select value={data.province} onChange={e => update('province', e.target.value)} className={S}>
                                {PROVINCES.map(p => <option key={p}>{p}</option>)}
                            </select>
                        </div>
                        <div className="space-y-1.5">
                            <label className={L}>Postal Code</label>
                            <input value={data.postalCode} onChange={e => update('postalCode', e.target.value)} placeholder="M5V 2T6" className={cn(I, 'font-mono')} />
                        </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                            <label className={L}>Timezone</label>
                            <select value={data.timezone} onChange={e => update('timezone', e.target.value)} className={S}>
                                {TIMEZONES.map(tz => <option key={tz}>{tz}</option>)}
                            </select>
                        </div>
                        <div className="grid grid-cols-2 gap-3">
                            <div className="space-y-1.5">
                                <label className={L}><Hash size={10} /> Lat</label>
                                <input type="number" step="any" value={data.latitude} onChange={e => update('latitude', e.target.value)} placeholder="43.6532" className={cn(I, 'font-mono text-xs')} />
                            </div>
                            <div className="space-y-1.5">
                                <label className={L}><Hash size={10} /> Lng</label>
                                <input type="number" step="any" value={data.longitude} onChange={e => update('longitude', e.target.value)} placeholder="-79.3832" className={cn(I, 'font-mono text-xs')} />
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Contact */}
            <section>
                <h4 className="text-[11px] font-black text-slate-600 uppercase tracking-[0.15em] mb-4 flex items-center gap-2">
                    <span className="w-1 h-4 rounded-full bg-violet-500" />
                    <Phone size={13} /> Contact
                </h4>
                <div className="grid grid-cols-3 gap-4">
                    <div className="space-y-1.5">
                        <label className={L}><Phone size={10} /> Phone</label>
                        <input type="tel" value={data.phone} onChange={e => update('phone', e.target.value)} placeholder="+1 (416) 555-0100" className={I} />
                    </div>
                    <div className="space-y-1.5">
                        <label className={L}><Phone size={10} /> Secondary Phone</label>
                        <input type="tel" value={data.secondaryPhone} onChange={e => update('secondaryPhone', e.target.value)} placeholder="+1 (416) 555-0101" className={I} />
                    </div>
                    <div className="space-y-1.5">
                        <label className={L}><Mail size={10} /> Email</label>
                        <input type="email" value={data.email} onChange={e => update('email', e.target.value)} placeholder="store@brand.com" className={I} />
                    </div>
                </div>
            </section>
        </div>
    );
}
