'use client';

import React from 'react';
import { Phone, Bot, Key, Globe, AlertCircle, Shield, Copy, CheckCircle2 } from 'lucide-react';
import { FormSectionTitle, InputWrapper, INPUT_CLASS } from './ui';
import type { OnboardingVapiConfig } from '../types/onboarding.types';

interface VapiConfigStepProps {
    vapi: OnboardingVapiConfig;
    onUpdate: (updates: Partial<OnboardingVapiConfig>) => void;
}

export function VapiConfigStep({ vapi, onUpdate }: VapiConfigStepProps) {
    const [copied, setCopied] = React.useState(false);

    // Webhook URL will be generated after tenant creation —
    // show placeholder format so the Super Admin knows what to expect
    const webhookUrlPreview = 'https://api.zyappy.com/api/call-analysis/webhook?tenant_token=<auto-generated>';

    const handleCopyWebhook = async () => {
        try {
            await navigator.clipboard.writeText(webhookUrlPreview);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch { /* clipboard API not available */ }
    };

    return (
        <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Info Banner */}
            <section className="bg-gradient-to-br from-violet-50 to-indigo-50 p-8 rounded-3xl border border-violet-200 shadow-sm space-y-4">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-violet-600 flex items-center justify-center shadow-lg shadow-violet-200">
                        <Bot className="w-5 h-5 text-white" />
                    </div>
                    <div>
                        <h3 className="text-sm font-black text-violet-900">AI Call Analytics — Tenant Isolation</h3>
                        <p className="text-[10px] text-violet-600 font-medium mt-0.5">
                            Link this tenant to their Vapi assistant for isolated call data, transcripts, and analytics.
                        </p>
                    </div>
                </div>
                <div className="flex items-start gap-3 p-4 bg-white/60 border border-violet-100 rounded-2xl">
                    <AlertCircle className="w-4 h-4 text-violet-500 mt-0.5 shrink-0" />
                    <p className="text-[10px] text-violet-700 font-medium leading-relaxed">
                        When Vapi sends a webhook, we resolve the tenant using the <span className="font-black">Assistant ID</span>. 
                        This ensures call data is isolated — each tenant only sees their own calls, transcripts, and sentiment reports.
                    </p>
                </div>
            </section>

            {/* Assistant Configuration */}
            <section className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm space-y-6">
                <FormSectionTitle icon={Key} title="Vapi Assistant Credentials" />
                <p className="text-xs text-slate-500 font-medium leading-relaxed -mt-4">
                    Enter the Vapi Assistant ID and phone number created for this tenant in the Vapi dashboard.
                </p>

                <div className="grid grid-cols-1 gap-6">
                    <InputWrapper label="Vapi Assistant ID" required>
                        <div className="relative">
                            <Bot className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                            <input
                                type="text"
                                value={vapi.assistantId}
                                onChange={(e) => onUpdate({ assistantId: e.target.value })}
                                placeholder="e.g. asst_abc123def456..."
                                className={`${INPUT_CLASS} pl-11 font-mono text-xs`}
                            />
                        </div>
                    </InputWrapper>

                    <InputWrapper label="Assistant Phone Number" required>
                        <div className="relative">
                            <Phone className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                            <input
                                type="tel"
                                value={vapi.phoneNumber}
                                onChange={(e) => onUpdate({ phoneNumber: e.target.value })}
                                placeholder="+1 (555) 000-0000"
                                className={`${INPUT_CLASS} pl-11 font-mono`}
                            />
                        </div>
                    </InputWrapper>
                </div>

                {(!vapi.assistantId || !vapi.phoneNumber) && (
                    <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-2xl">
                        <AlertCircle className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
                        <p className="text-[10px] text-amber-700 font-medium">
                            Both fields are required. Without an Assistant ID, webhook calls cannot be routed to this tenant.
                        </p>
                    </div>
                )}
            </section>

            {/* Webhook URL Preview */}
            <section className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm space-y-6">
                <FormSectionTitle icon={Globe} title="Webhook Endpoint" />
                <p className="text-xs text-slate-500 font-medium leading-relaxed -mt-4">
                    After provisioning, configure this URL in Vapi&apos;s Server URL field. A unique <code className="text-[10px] bg-slate-100 px-1.5 py-0.5 rounded font-mono">tenant_token</code> will be auto-generated.
                </p>

                <div className="flex items-center gap-3 p-4 bg-slate-900 rounded-2xl">
                    <code className="text-[10px] text-emerald-400 font-mono flex-1 break-all leading-relaxed">
                        {webhookUrlPreview}
                    </code>
                    <button
                        onClick={handleCopyWebhook}
                        className="shrink-0 p-2 rounded-lg bg-white/10 hover:bg-white/20 transition-colors"
                        title="Copy webhook URL"
                    >
                        {copied ? (
                            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                        ) : (
                            <Copy className="w-4 h-4 text-slate-400" />
                        )}
                    </button>
                </div>
            </section>

            {/* Security Note */}
            <div className="flex items-start gap-3 p-5 bg-slate-50 border border-slate-200 rounded-2xl">
                <Shield className="w-4 h-4 text-slate-400 mt-0.5 shrink-0" />
                <p className="text-[10px] text-slate-500 font-medium leading-relaxed">
                    The webhook token is cryptographically generated and unique per tenant. It validates that incoming Vapi webhooks are authentic and maps them to the correct tenant&apos;s data store.
                </p>
            </div>
        </div>
    );
}
