import { Campaign } from '../types/campaign.types';

export const DEV_SEED_CAMPAIGNS: Campaign[] = [
    {
        id: 'camp-001',
        name: 'Spring Collection Launch',
        subject: '🌸 Our Spring Collection is Here!',
        previewText: 'Be the first to shop our newest arrivals.',
        status: 'sent',
        audience: 'High-Value Customers',
        templateId: 'temp-001',
        senderName: 'Zyappy Fashion',
        replyTo: 'hello@zyappy.com',
        createdBy: 'Admin User',
        createdAt: '2026-03-10T10:00:00Z',
        scheduledAt: '2026-03-12T09:00:00Z',
    },
    {
        id: 'camp-002',
        name: 'Weekly Newsletter #42',
        subject: 'Weekly Digest: Tech Trends',
        previewText: 'Stay ahead of the curve with our weekly summary.',
        status: 'scheduled',
        audience: 'All Subscribers',
        templateId: 'temp-002',
        senderName: 'Zyappy Editorial',
        replyTo: 'news@zyappy.com',
        createdBy: 'Content Manager',
        createdAt: '2026-04-15T14:30:00Z',
        scheduledAt: '2026-04-20T10:00:00Z',
    },
    {
        id: 'camp-003',
        name: 'Abandoned Cart Reminder',
        subject: 'Did you forget something?',
        previewText: 'Your cart is waiting for you.',
        status: 'draft',
        audience: 'Recent Shoppers',
        templateId: 'temp-003',
        senderName: 'Zyappy Shop',
        replyTo: 'support@zyappy.com',
        createdBy: 'System',
        createdAt: '2026-04-17T09:15:00Z',
    },
    {
        id: 'camp-004',
        name: 'VIP Early Access',
        subject: 'Private Sale: Members Only',
        status: 'sending',
        audience: 'VIP Members',
        templateId: 'temp-001',
        senderName: 'Zyappy VIP',
        replyTo: 'vip@zyappy.com',
        createdBy: 'Marketing Director',
        createdAt: '2026-04-17T15:00:00Z',
        scheduledAt: '2026-04-17T16:00:00Z',
    },
    {
        id: 'camp-005',
        name: 'Flash Sale Alert',
        subject: '⚡ 24 Hours Only!',
        status: 'blocked',
        audience: 'All Contacts',
        templateId: 'temp-004',
        senderName: 'Zyappy',
        replyTo: 'deals@zyappy.com',
        createdBy: 'Admin User',
        createdAt: '2026-04-16T11:00:00Z',
    }
];
